// <auto-generated />
using System;
using GerenciadorDeContato.ClassLibrary.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerenciadorDeContato.ClassLibrary.Migrations
{
    [DbContext(typeof(DominioContext))]
    [Migration("20211004181227_CriandoTabelas")]
    partial class CriandoTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GerenciadorDeContato.ClassLibrary.Dominio.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("TBContato");
                });

            modelBuilder.Entity("GerenciadorDeContato.ClassLibrary.Dominio.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("contatoId")
                        .HasColumnType("int");

                    b.Property<int>("ddd")
                        .HasColumnType("INT");

                    b.Property<int>("numero")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("contatoId");

                    b.ToTable("TBTelefone");
                });

            modelBuilder.Entity("GerenciadorDeContato.ClassLibrary.Dominio.Telefone", b =>
                {
                    b.HasOne("GerenciadorDeContato.ClassLibrary.Dominio.Contato", "contato")
                        .WithMany("Telefones")
                        .HasForeignKey("contatoId");

                    b.Navigation("contato");
                });

            modelBuilder.Entity("GerenciadorDeContato.ClassLibrary.Dominio.Contato", b =>
                {
                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
